### ISSUE TITLE
Set up instructions

### ISSUE THREAD

**Issue by xQsme** [TehNut/CSGOPresence#6]
Hey mate, i have no idea how to get this working, i ran the bat file and made the cfg file but i don't think that's enough, can you update the readme with more info? Thanks

**Comment by TehNut** [comment]
Does the README explain it better now? You need to make sure you actually run the built jar.

E: There's a proper release [here](https://github.com/TehNut/CSGOPresence/releases/tag/v1.0.0).

**Comment by xQsme** [comment]
Thanks dude, got it working now, i guess I was missing the JDK

**Comment by TehNut** [comment]
Ah you shouldn't need the JDK if you use the prebuilt jars in the release tab.

**Comment by xQsme** [comment]
Also, on discord it doesnt say competitive, says unknown and instead of the team scores it tells my personal score, any idea why?

**Comment by TehNut** [comment]
I probably have the internal name wrong. I don't really play CS a whole lot anymore so I didn't want to jump into a comp game just to debug. I'll see if I can find a friend to carry me tonight so I can get the proper name.

**Comment by TehNut** [comment]
Opened as it's own issue at #7
