### ISSUE TITLE
Comp shows as unknown 

### ISSUE THREAD

**Issue by TehNut** [TehNut/CSGOPresence#7]
Internal name is wrong.

**Comment by xQsme** [comment]
Hey mate, i see comp is fixed and was a simple mistake, guess you can close this issue...
But when i end a game the rich presence stays on as if i'm still in my previous game, even when i close csgo completely...
Anyway, thx for this tool ;)

**Comment by TehNut** [comment]
Bah, I need to setup a proper release system so I stop forgetting about issues.

Rich presence *should* be detecting game closure and shutting down the connection. What OS are you running?

E: Actually could you open a new issue for that?
