### ISSUE TITLE
Presence runs as if i'm still in game when i've already finished

### ISSUE THREAD

**Issue by xQsme** [TehNut/CSGOPresence#8]
Windows 10 Version	10.0.16299 Build 16299

Steps to reproduce:
Play comp (maybe some other game modes not sure)
Finish game
Close cs:go (straight from competitive lobby to desktop)

What to expect:
Discord shows I'm in a competitive game with score 16-something
Shows my final weapon and current stats and the map that was being played

What should happen:
Update to "In menu" or not playing at all

Workaround:
only by closing the presence Jar will the discord info update that i'm no longer playing cs:go

**Comment by TehNut** [comment]
In your console (if you run it from that), it should have some log output whenever you open or close the game about detecting it. Does that show up?

**Comment by xQsme** [comment]
I've usualy just ran the jar file, i can try that later when i play a comp
Tried it in a custom map and it appeared to work fine, it does detect the game closing but discord still shows as i'm in menu
"CSGO not detected. Shutting down RPC."

**Comment by TehNut** [comment]
I'm not actually able to reproduce this. Could you try with this jar? https://waifu.me/file/CSGOPresence-1.0.2pre-all.jar

**Comment by xQsme** [comment]
That jar is indeed different from mine, hopping into a comp game soon, I'll tell you after if it was my jar's fault

**Comment by xQsme** [comment]
same results from playing comp, tried a custom map after and it did work as intended
